[workspace]
members = [
    "auther",
    "crypter",
    "glyph",
    "signer",
    "sphinx-frost",
    "sphinx-frost-musig",
    "sphinx-musig",
    "vls-mqtt",
]

exclude = [
    "sphinx-ffi",
    "sphinx-wasm",
]
