[workspace]
members = [
    "auther",
    "crypter",
    "glyph",
    "signer",
    "vls-mqtt",
    "lss-connector"
]

exclude = [
    "sphinx-ffi",
    "sphinx-frost",
    "sphinx-wasm",
    "rmp-utils",
]
