[package]
name = "sphinx-glyph"
version = "0.1.0"
authors = ["Evan Feenstra <evanfeenstra@gmail.com>"]
edition = "2018"
description = "Sphinx lightning hardware signer"
repository = "https://github.com/stakwork/sphinx-rs"
license = "MIT"

[dependencies]
sphinx-auther = { path = "../auther", version = "0.1.10" }
anyhow = "1"
serde = { version = "1.0", default-features = false, features = ["derive"] }
rmp-serde = "1.1.0"
serde_json = "1.0.86"