[package]
name = "sphinx-signer"
version = "0.1.0"
authors = ["Evan Feenstra <evanfeenstra@gmail.com>"]
edition = "2018"
description = "Sphinx lightning hardware signer"
repository = "https://github.com/stakwork/sphinx-rs"
license = "MIT"

[features]
default = ["fspersist"]
fspersist = ["fsdb", "vls-persist"]

[dependencies]
sphinx-glyph = { path = '../glyph' }
lss-connector = { path = "../lss-connector", default-features = false }
# sphinx-glyph = "0.1.2"
vls-protocol-signer = { git = "https://gitlab.com/lightning-signer/validating-lightning-signer.git", rev = "0c8c4474af62c4a13e2a32d34b569e8092ed414a", default-features = false, features = ["std", "secp-lowmemory"] }
vls-protocol = { git = "https://gitlab.com/lightning-signer/validating-lightning-signer.git", rev = "0c8c4474af62c4a13e2a32d34b569e8092ed414a", features = ["std"] }
vls-persist = { git = "https://gitlab.com/lightning-signer/validating-lightning-signer.git", rev = "0c8c4474af62c4a13e2a32d34b569e8092ed414a", default-features = false, features = ["std", "memo"], optional = true }
log = "0.4"
rand = "0.8"
serde = "1.0.1"
hex = "0.4.3"
bip39 = "1.0.1"
anyhow = "1"
fsdb = { version = "0.1.11", optional = true }


