[package]
name = "sphinx-signer"
version = "0.1.0"
authors = ["Evan Feenstra <evanfeenstra@gmail.com>"]
edition = "2018"
description = "Sphinx lightning hardware signer"
repository = "https://github.com/stakwork/sphinx-rs"
license = "MIT"

[features]
default = ["fspersist", "vls-persist", "std"]
fspersist = ["fsdb", "vls-persist/memo"]
persist = ["vls-persist"]
std = ["vls-persist/std", "vls-protocol-signer/std", "vls-protocol/std", "lss-connector/std"]
broker-test = ["lss-connector/broker"]
no-std = ["vls-protocol-signer/no-std", "vls-persist/no-std", "lss-connector/no-std"]

[dependencies]
sphinx-glyph = { path = '../glyph' }
lss-connector = { path = "../lss-connector", default-features = false }
vls-protocol-signer = { git = "https://gitlab.com/lightning-signer/validating-lightning-signer.git", rev = "163bade8dc4a97fdb516b68fbfdff8e43a74e795", default-features = false, features = ["secp-lowmemory"] }
vls-protocol = { git = "https://gitlab.com/lightning-signer/validating-lightning-signer.git", rev = "163bade8dc4a97fdb516b68fbfdff8e43a74e795" }
vls-persist = { git = "https://gitlab.com/lightning-signer/validating-lightning-signer.git", rev = "163bade8dc4a97fdb516b68fbfdff8e43a74e795", default-features = false, features = ["memo"], optional = true }
# vls-protocol-signer = { path = "../../../evanf/vls-evanf/vls-protocol-signer", default-features = false, features = ["secp-lowmemory"] }
# vls-protocol = { path = "../../../evanf/vls-evanf/vls-protocol" }
# vls-persist = { path = "../../../evanf/vls-evanf/vls-persist", default-features = false, features = ["memo"], optional = true }
log = "0.4"
rand = "0.8"
serde = { version = "1.0.168", default-features = false, features = ["derive"] }
hex = "0.4.3"
bip39 = "1.0.1"
anyhow = "1"
fsdb = { version = "0.1.11", optional = true }


