[package]
name = "lss-connector"
version = "0.1.0"
authors = ["Evan Feenstra <evanfeenstra@gmail.com>"]
edition = "2018"
description = "LSS connector utils"
repository = "https://github.com/stakwork/sphinx-rs"
license = "MIT"

[features]
default = ["broker"]
broker = ["lightning-storage-server", "vls-frontend"]

[dependencies]
vls-protocol-signer = { git = "https://gitlab.com/lightning-signer/validating-lightning-signer.git", rev = "e13c8cd994b310f598c0b2902741d89ad5472382", default-features = false, features = ["std", "secp-lowmemory"] }
lightning-storage-server = { git = "https://gitlab.com/lightning-signer/validating-lightning-signer.git", rev = "e13c8cd994b310f598c0b2902741d89ad5472382", optional = true }
vls-frontend = { git = "https://gitlab.com/lightning-signer/validating-lightning-signer.git", rev = "e13c8cd994b310f598c0b2902741d89ad5472382", optional = true }
log = "0.4"
serde = "1.0.1"
anyhow = "1"
secp256k1 = { version = "0.24.0", features = ["rand-std", "bitcoin_hashes"] }
tokio = "1"
rmp-serde = "1.1.0"
hex = "0.4.3"
