[package]
name = "lss-connector"
version = "0.1.0"
authors = ["Evan Feenstra <evanfeenstra@gmail.com>"]
edition = "2018"
description = "LSS connector utils"
repository = "https://github.com/stakwork/sphinx-rs"
license = "MIT"

[features]
default = ["broker"]
broker = ["lightning-storage-server", "vls-frontend", "tokio"]

[dependencies]
sphinx-glyph = { path = '../glyph' }
vls-protocol-signer = { git = "https://gitlab.com/lightning-signer/validating-lightning-signer.git", rev = "95a152dce73ea7d9d10dc4ba50f43c3a0af05df8", default-features = false, features = ["std", "secp-lowmemory"] }
# vls-protocol-signer = { path = "../../validating-lightning-signer/vls-protocol-signer", default-features = false, features = ["std", "secp-lowmemory"] }
log = "0.4"
serde = "1.0.1"
anyhow = "1"
secp256k1 = { version = "0.24.0", features = ["rand-std", "bitcoin_hashes"] }
rmp-serde = "1.1.0"
serde-big-array = "0.5.1"
# broker libs
lightning-storage-server = { git = "https://gitlab.com/lightning-signer/validating-lightning-signer.git", rev = "95a152dce73ea7d9d10dc4ba50f43c3a0af05df8", optional = true }
vls-frontend = { git = "https://gitlab.com/lightning-signer/validating-lightning-signer.git", rev = "95a152dce73ea7d9d10dc4ba50f43c3a0af05df8", optional = true }
# lightning-storage-server = { path = "../../validating-lightning-signer/lightning-storage-server", optional = true }
# vls-frontend = { path = "../../validating-lightning-signer/vls-frontend", optional = true }
tokio = { version = "1.27", features = ["macros", "rt-multi-thread"], optional = true }


